### ISSUE TITLE
Bugs & roadmap for initial paper release

### ISSUE THREAD

**Issue by DanInci** [omnibenchmark/omnibenchmark#40]
Features:
- [ ] Create a clustering benchmark using omnibenchmark ---> #
- [ ] CI & CD example for continous benchmarking ---> #34 
- [ ] Formalize metrics
- [ ] Add profiling capabilities for module execution
- [ ] Benchmark version archiving ---> #37 

Major bugs:
- [ ] Snakemake execution environment is coupled to setup environment ---> #39 
- [ ] 

Minor bugs:
- [ ] envmodules environment setup leaks
